### ISSUE TITLE
Cursor keys don't work under OSX

### ISSUE THREAD

**Issue by dwjoyce** [matsjoyce/pygame-quick#1]
The cursor keys do not work under OSX - instead of receiving a "<Left>" key, I instead get a "uf703" key instead.  The event type is key_down, as it should be.

Not sure if this helps, but I found this information:
http://sbnes.livejournal.com/3725.html

**Comment by matsjoyce** [comment]
Could you try with 1314642a7c6708918c52cf34437dc3e03be5f027?
